import type { Db } from "@/lib/db";
import { ApiError } from "@/lib/http/errors";
import { formatAud } from "@/lib/money";
import { getStripe } from "./stripe";
import { logAction, type Actor } from "@/lib/audit";
import { markOrderRefunded } from "@/lib/shop/orders";
import { sendOrderEmail } from "@/lib/shop/emails";
import { assertLocation, type LocationScope } from "@/lib/locations/scope";

export interface RefundInput {
  paymentId: string;
  amountCents: number;
  reason: string;
  // STRIPE refunds the card. MANUAL records money returned another way.
  method: "STRIPE" | "MANUAL";
  // One ID per refund attempt, generated by the browser when the refund form
  // opens. Retrying the same attempt reuses Stripe's idempotency key, so the
  // card can't be refunded twice (R-10).
  requestId?: string;
}

// GST on a partial refund is the payment's GST in proportion to what has been
// refunded so far, minus what earlier refunds already took. Working it out
// cumulatively means the parts always add up to the payment's GST (R-17).
// It follows the GST recorded on the payment, whatever the gym's registration
// is today (R-73, D-121).
export function refundGst(payment: { amount: number; gstCents: number }, alreadyRefundedCents: number, refundCents: number): number {
  if (payment.amount <= 0 || payment.gstCents <= 0) return 0;
  const share = (refundedCents: number) => Math.round((payment.gstCents * refundedCents) / payment.amount);
  return share(alreadyRefundedCents + refundCents) - share(alreadyRefundedCents);
}

export function statusAfterRefunds(amountCents: number, refundedCents: number, current: string): string {
  if (refundedCents >= amountCents) return "refunded";
  if (refundedCents > 0) return "partially_refunded";
  return current;
}

export async function refundPayment(db: Db, actor: Actor & { kind: "staff" }, input: RefundInput) {
  const payment = await db.payment.findUnique({ where: { id: input.paymentId } });
  if (!payment) throw new ApiError("not_found", "Payment not found.");
  // Staff limited to some locations refund only their locations' payments (D-128).
  if ("locationIds" in actor) assertLocation(actor as unknown as LocationScope, payment.locationId);
  const refundable = payment.amount - payment.refundedCents;
  if (input.amountCents <= 0) throw new ApiError("validation_failed", "Enter an amount above zero.", { amountCents: "Above zero" });
  if (input.amountCents > refundable) {
    throw new ApiError("validation_failed", `At most ${formatAud(refundable)} can be refunded on this payment.`, { amountCents: "Too much" });
  }

  let stripeRefundId: string | null = null;
  if (input.method === "STRIPE") {
    if (!payment.stripePaymentIntentId) {
      throw new ApiError("conflict", "This payment didn't go through Stripe. Record a manual refund instead.");
    }
    const idempotencyKey = input.requestId ? `refund-${payment.id}-${input.requestId}` : `refund-${payment.id}-${payment.refundedCents}-${input.amountCents}`;
    try {
      const refund = await getStripe().refunds.create(
        { payment_intent: payment.stripePaymentIntentId, amount: input.amountCents, metadata: { paymentId: payment.id } },
        { idempotencyKey }
      );
      stripeRefundId = refund.id;
    } catch (error) {
      if (error instanceof ApiError) throw error;
      throw new ApiError("upstream_failed", "Stripe couldn't process the refund. Nothing was recorded. Try again shortly.");
    }
  }

  let orderToEmail: string | null = null;
  const refund = await db.$transaction(async (tx) => {
    // The payment row is locked, so concurrent refunds (or the webhook for
    // this same refund) run one after the other and see each other's totals.
    await tx.$queryRaw`SELECT "id" FROM "Payout" WHERE "id" = ${payment.id} FOR UPDATE`;
    if (stripeRefundId) {
      // Stripe's webhook may have recorded this refund already, or this is a
      // retry of an attempt that succeeded: either way it's done.
      const recorded = await tx.refund.findUnique({ where: { stripeRefundId } });
      if (recorded) return recorded;
    }
    const current = await tx.payment.findUniqueOrThrow({ where: { id: payment.id }, include: { order: { select: { id: true } } } });
    if (current.refundedCents + input.amountCents > current.amount) {
      throw new ApiError("conflict", "Another refund changed this payment. Reload and try again.");
    }
    const gst = refundGst(current, current.refundedCents, input.amountCents);
    const refundedCents = current.refundedCents + input.amountCents;
    await tx.payment.update({ where: { id: payment.id }, data: { refundedCents, status: statusAfterRefunds(current.amount, refundedCents, current.status) } });
    const created = await tx.refund.create({
      data: { paymentId: payment.id, amountCents: input.amountCents, gstCents: gst, reason: input.reason, stripeRefundId, method: input.method, staffId: actor.id, staffName: actor.name },
    });
    if (current.order && refundedCents >= current.amount && (await markOrderRefunded(tx, current.order.id, input.reason, actor.name))) {
      orderToEmail = current.order.id;
    }
    await logAction(tx, actor, {
      action: "billing.refunded",
      targetType: "Payment",
      targetId: payment.id,
      details: { amountCents: input.amountCents, gstCents: gst, method: input.method, reason: input.reason, invoiceNumber: payment.invoiceNumber },
      before: { refundedCents: current.refundedCents, status: current.status },
      after: { refundedCents, status: statusAfterRefunds(current.amount, refundedCents, current.status) },
    });
    return created;
  });
  if (orderToEmail) await sendOrderEmail(db, orderToEmail, "refunded").catch(() => undefined);
  return refund;
}
