import type { Permission } from "./permissions";

export const PERMISSION_TEXT: Record<Permission, string> = {
  "dashboard:view": "See the dashboard",
  "revenue:view": "See revenue and payments",
  "members:read": "See members",
  "members:write": "Add members, edit details, write notes",
  "members:archive": "Archive members",
  "plans:manage": "Create plans and set prices",
  "billing:manage": "Change plans, pause, cancel, adjust benefits",
  "billing:refund": "Refund payments",
  "finance:view": "See finance reports and exports",
  "shop:manage": "Add and edit shop products",
  "orders:fulfil": "Pack and hand over shop orders",
  "classes:read": "See classes",
  "classes:manage": "Create classes and the timetable",
  "classes:book": "Book members into classes",
  "classes:attendance": "Mark attendance",
  "checkin:scan": "Check members in",
  "staff:read": "See staff",
  "staff:manage": "Add and remove staff, change roles",
  "shifts:read": "See the roster",
  "shifts:manage": "Change the roster",
  "audit:read": "See the audit log",
  "settings:manage": "Change gym settings",
  "equipment:read": "See equipment",
  "equipment:manage": "Approve repairs",
  "inventory:read": "See stock",
  "inventory:adjust": "Adjust stock counts",
  "inventory:manage": "Add and edit stock items",
  "announcements:manage": "Post announcements",
};
